Implement loading animations and notifications at specific values
soaple/stickyboard-mqtt pull request #1
Opened 2020-09-05 12:25 UTC by ChanggeonLee

Implemented to perform loading animation while connected to MQTT server
Implemented to blink red and blue according to the set MAX and MIN

2020-09-05 16:28 UTC, soaple commented on package.json
> +        "@material-ui/core": "^4.11.0",
Material-UI is too big package.
So, how about using the package below, if you just intend to use progress.
[https://github.com/davidhu2000/react-spinners](url)

2020-09-05 16:29 UTC, soaple requested changes
Please check the comments.

2020-09-06 13:16 UTC, ChanggeonLee commented
Change package from material-ui to react-spinners

2020-09-06 15:35 UTC, soaple approved these changes
LGTM (Looks Good To Me)

2020-09-06 15:36 UTC, merged